name: Deploy Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy website
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: 22
        key: ${{ secrets.ACCESS_TOKEN }}
        source: "public/*"
        target: "test"
        # SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        # ARGS: "-avz --delete"
        # SOURCE: "public/"
        # REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # TARGET: ${{ secrets.REMOTE_TARGET }}